# Generated by Django 2.2.13 on 2022-02-28 17:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_auto_20210907_0047'), ('users', '0003_auto_20210917_0018'), ('users', '0004_after10'), ('users', '0005_after12arts_after12commerce_after12science'), ('users', '0006_after10colleges_after12colleges'), ('users', '0007_auto_20211014_1808'), ('users', '0008_auto_20211014_1829'), ('users', '0009_auto_20211014_1839'), ('users', '0010_auto_20211014_1839'), ('users', '0011_auto_20211014_1846'), ('users', '0012_rename_after12colleges_after12engcolleges'), ('users', '0013_after12medicolleges'), ('users', '0014_after12artscolleges_after12commcolleges'), ('users', '0015_after10colleges_website'), ('users', '0016_auto_20211014_2149'), ('users', '0017_auth_user'), ('users', '0018_auto_20211016_2127'), ('users', '0019_user_password'), ('users', '0020_auto_20220118_1538'), ('users', '0021_result_username'), ('users', '0022_alter_result_username'), ('users', '0023_result12arts'), ('users', '0024_result12comm'), ('users', '0025_result12sci'), ('users', '0026_delete_after10'), ('users', '0027_after10'), ('users', '0028_after10_question_type'), ('users', '0029_auto_20220131_1138'), ('users', '0030_auto_20220131_1140'), ('users', '0031_result10count'), ('users', '0032_auto_20220207_1340'), ('users', '0033_result_correct_answer'), ('users', '0034_remove_result_correct_answer'), ('users', '0035_result_correct_answer'), ('users', '0036_rename_correct_answer_result_correct_ans'), ('users', '0037_auto_20220207_1359'), ('users', '0038_auto_20220207_1402'), ('users', '0039_remove_result_correct_ans'), ('users', '0040_auto_20220207_1417'), ('users', '0041_auto_20220207_1419'), ('users', '0042_auto_20220207_1426'), ('users', '0043_remove_result_correct_answer'), ('users', '0044_alter_result12comm_answer'), ('users', '0045_result10count_count_diploma'), ('users', '0046_remove_result10count_count_diploma'), ('users', '0047_auto_20220207_1848'), ('users', '0048_after10_result_result10count'), ('users', '0049_alter_result_answer'), ('users', '0050_alter_after10_id'), ('users', '0051_alter_after10_id'), ('users', '0052_auto_20220228_2310')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='After12Arts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=900, unique=True)),
                ('correct_answer', models.CharField(default=' ', max_length=120)),
                ('op1', models.CharField(max_length=900, null=True)),
                ('op2', models.CharField(max_length=900, null=True)),
                ('op3', models.CharField(max_length=900, null=True)),
                ('op4', models.CharField(max_length=900, null=True)),
                ('question_type', models.CharField(default=' ', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='After12Commerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='After12Science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='After10colleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_address', models.CharField(default='', max_length=1000)),
                ('college_name', models.CharField(default='', max_length=1000)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('website', models.URLField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='After12artscolleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='', max_length=1000)),
                ('college_address', models.CharField(default='', max_length=1000)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('website', models.URLField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='After12commcolleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='', max_length=1000)),
                ('college_address', models.CharField(default='', max_length=1000)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('website', models.URLField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='After12engcolleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_address', models.CharField(default='', max_length=1000)),
                ('college_name', models.CharField(default='', max_length=1000)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('website', models.URLField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='After12medicolleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='', max_length=1000)),
                ('college_address', models.CharField(default='', max_length=1000)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('website', models.URLField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('aadhar_no', models.CharField(max_length=100)),
                ('email_token', models.CharField(blank=True, max_length=100, null=True)),
                ('forget_password', models.CharField(blank=True, max_length=100, null=True)),
                ('last_login', models.CharField(blank=True, max_length=100, null=True)),
                ('last_logout', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('test_after', models.CharField(default='', max_length=100)),
                ('user_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='result12arts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(blank=True, max_length=254)),
                ('question', models.CharField(default='', max_length=255)),
                ('answer', models.CharField(default='', max_length=255)),
                ('question_type', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='result12sci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(blank=True, max_length=254)),
                ('question', models.CharField(default='', max_length=1000)),
                ('answer', models.CharField(choices=[('Dislike', 'Dislike'), ('Neutral', 'Neutral'), ('Enjoy', 'Enjoy')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='result12comm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(blank=True, max_length=254)),
                ('question', models.CharField(default='', max_length=1000)),
                ('answer', models.CharField(choices=[('Dislike', 'Dislike'), ('Neutral', 'Neutral'), ('Enjoy', 'Enjoy')], max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Result12artsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('count_ID', models.CharField(max_length=10)),
                ('count_Journalism', models.CharField(max_length=10)),
                ('count_Fashion', models.CharField(max_length=10)),
                ('count_Hotel', models.CharField(default=' ', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='After10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=900, unique=True)),
                ('question_type', models.CharField(default=' ', max_length=120)),
                ('op1', models.CharField(max_length=900, null=True)),
                ('op2', models.CharField(max_length=900, null=True)),
                ('op3', models.CharField(max_length=900, null=True)),
                ('op4', models.CharField(max_length=900, null=True)),
                ('correct_answer', models.CharField(default=' ', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(blank=True, max_length=254)),
                ('question', models.CharField(default='', max_length=1000)),
                ('answer', models.CharField(default='', max_length=900)),
                ('question_type', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Result10Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('count_science', models.CharField(max_length=10)),
                ('count_arts', models.CharField(max_length=10)),
                ('count_commerce', models.CharField(max_length=10)),
                ('count_diploma', models.CharField(default=' ', max_length=10)),
            ],
        ),
    ]
