# Generated by Django 2.2.13 on 2022-03-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0052_auto_20220228_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result12commerceCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('count_BCOM', models.CharField(max_length=10)),
                ('count_BAF', models.CharField(max_length=10)),
                ('count_BMS', models.CharField(max_length=10)),
                ('count_CA', models.CharField(default=' ', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='result12comm',
            name='question_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='result12comm',
            name='answer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='result12comm',
            name='question',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='test_after',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(max_length=100),
        ),
    ]
