# Generated by Django 2.2.13 on 2022-03-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220301_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='after12commerce',
            name='correct_answer',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AddField(
            model_name='after12commerce',
            name='op1',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after12commerce',
            name='op2',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after12commerce',
            name='op3',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after12commerce',
            name='op4',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after12commerce',
            name='question_type',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AlterField(
            model_name='after12commerce',
            name='question',
            field=models.CharField(max_length=900, unique=True),
        ),
    ]
