# Generated by Django 2.2.13 on 2022-03-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220301_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result12sciencecount',
            old_name='count_BAF',
            new_name='count_avi',
        ),
        migrations.RenameField(
            model_name='result12sciencecount',
            old_name='count_CA',
            new_name='count_bsc',
        ),
        migrations.RenameField(
            model_name='result12sciencecount',
            old_name='count_BCOM',
            new_name='count_engg',
        ),
        migrations.RenameField(
            model_name='result12sciencecount',
            old_name='count_BMS',
            new_name='count_mbbs',
        ),
    ]
