# Generated by Django 3.2.7 on 2022-02-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_result10count'),
    ]

    operations = [
        migrations.AddField(
            model_name='after10',
            name='correct_answer',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AddField(
            model_name='after10',
            name='op1',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after10',
            name='op2',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after10',
            name='op3',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after10',
            name='op4',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='after10',
            name='question',
            field=models.CharField(max_length=900, unique=True),
        ),
    ]
