# Generated by Django 3.2.7 on 2022-02-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20220207_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='after10',
            old_name='answer',
            new_name='correct_answer',
        ),
        migrations.AddField(
            model_name='result',
            name='correct_ans',
            field=models.CharField(default=' ', max_length=120),
        ),
    ]
