# Generated by Django 3.2.7 on 2022-02-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20220207_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='after10',
            old_name='answer',
            new_name='correct_answer',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='correct_ans',
            new_name='correct_answer',
        ),
    ]
