# Generated by Django 3.2.7 on 2022-02-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_result12comm_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='result10count',
            name='count_diploma',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
