# Generated by Django 3.2.7 on 2022-02-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_result10count_count_diploma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result10count',
            name='count_diploma',
        ),
    ]
