# Generated by Django 3.2.7 on 2022-02-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_remove_result10count_count_diploma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='After10',
        ),
        migrations.DeleteModel(
            name='result',
        ),
        migrations.DeleteModel(
            name='Result10Count',
        ),
    ]
