# Generated by Django 3.2.7 on 2022-02-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alter_result_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='after10',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
