# Generated by Django 2.2.13 on 2022-02-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_alter_after10_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result12artsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('count_ID', models.CharField(max_length=10)),
                ('count_Journalism', models.CharField(max_length=10)),
                ('count_Fashion', models.CharField(max_length=10)),
                ('count_Hotel', models.CharField(default=' ', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='after12arts',
            name='correct_answer',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AddField(
            model_name='after12arts',
            name='op1',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after12arts',
            name='op2',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after12arts',
            name='op3',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after12arts',
            name='op4',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='after12arts',
            name='question_type',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AddField(
            model_name='result12arts',
            name='question_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='after10',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='after10colleges',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='after12arts',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='after12arts',
            name='question',
            field=models.CharField(max_length=900, unique=True),
        ),
        migrations.AlterField(
            model_name='after12artscolleges',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='after12commcolleges',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='after12commerce',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='after12engcolleges',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='after12medicolleges',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='after12science',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='result',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='result10count',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='result12arts',
            name='answer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='result12arts',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='result12arts',
            name='question',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='result12comm',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='result12sci',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
